export * from "./authorization/authorization.jsx"
export * from "./registration/registration.jsx"
export * from "./main-page/main-page.jsx"
export * from "./users/users.jsx"
export * from "./catalog/catalog.jsx"
export * from "./product/product.jsx"
